version: "3.9"

services:
  redis:
    image: redis
    networks:
      - redis_net
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres_net
    restart: unless-stopped

  trade:
    depends_on:
      - redis
    build:
      context: ./services/trade
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

  payment:
    depends_on:
      - redis
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

  reporting:
    depends_on:
      - redis
    build:
      context: ./services/reporting
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

  api-gateway:
    depends_on:
      - redis
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
    ports:
      - "3000:3000"
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
  postgres_net:
    driver: bridge
volumes:
    postgres:
