version: "3.9"

services:
  redis:
    image: redis
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  trade:
    depends_on:
      - redis
    build:
      context: ./services/trade
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-postgres}
    restart: always

  payment:
    depends_on:
      - redis
    build:
      context: ./services/payment
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-postgres}
    restart: always


  reporting:
    depends_on:
      - redis
    build:
      context: ./services/reporting
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-postgres}
    restart: always

  api-gateway:
    depends_on:
      - redis
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    ports:
      - "3000:3000"
    restart: always



volumes:
    postgres:
